# -*- mode: ruby -*-
# vi: set ft=ruby :

CONFIG_VER = 2
Vagrant.configure(CONFIG_VER) do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "pharm.dv.net"
  config.vm.network "private_network", ip: "192.168.7.2"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "pharm1"
    vb.memory = 2048
    vb.cpus = 2
  end

  #config.vm.synced_folder "data", "/sdata"
  config.vm.provision "shell", path: "base.sh"
  config.vm.provision "shell", path: "envconfig.sh"
end
